version: "3.3"
services:
  app:
    build: .
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "4000:8000"
    env_file: .env
    volumes:
      - .:/usr/src/app




#   # database containers, one for each db
#   database1:
#     image: postgres:10
#     volumes:
#       - database1_volume:/var/lib/postgresql/data
#     env_file:
#       - config/db/database1_env
#     networks:
#       - database1_network


# volumes:
#   database1_volume:
#   static:
#   media:
